###################################################################

# Created by write_sdc on Tue Jun  2 02:27:10 2026

###################################################################
set sdc_version 2.2

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_transition 0.1 [current_design]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[31]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[30]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[29]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[28]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[27]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[26]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[25]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[24]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[23]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[22]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[21]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[20]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[19]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[18]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[17]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[16]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[15]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[14]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[13]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[12]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[11]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[10]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[9]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[8]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[7]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[6]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[5]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[4]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[3]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[2]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[1]}]
set_load -pin_load 0.1 [get_ports {o_imem_raddr[0]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[31]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[30]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[29]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[28]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[27]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[26]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[25]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[24]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[23]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[22]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[21]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[20]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[19]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[18]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[17]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[16]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[15]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[14]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[13]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[12]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[11]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[10]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[9]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[8]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[7]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[6]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[5]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[4]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[3]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[2]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[1]}]
set_load -pin_load 0.1 [get_ports {o_dmem_addr[0]}]
set_load -pin_load 0.1 [get_ports o_dmem_ren]
set_load -pin_load 0.1 [get_ports o_dmem_wen]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[31]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[30]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[29]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[28]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[27]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[26]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[25]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[24]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[23]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[22]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[21]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[20]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[19]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[18]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[17]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[16]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[15]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[14]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[13]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[12]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[11]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[10]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[9]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[8]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[7]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[6]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[5]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[4]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[3]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[2]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[1]}]
set_load -pin_load 0.1 [get_ports {o_dmem_wdata[0]}]
set_load -pin_load 0.1 [get_ports {o_dmem_mask[3]}]
set_load -pin_load 0.1 [get_ports {o_dmem_mask[2]}]
set_load -pin_load 0.1 [get_ports {o_dmem_mask[1]}]
set_load -pin_load 0.1 [get_ports {o_dmem_mask[0]}]
set_load -pin_load 0.1 [get_ports o_retire_valid]
set_load -pin_load 0.1 [get_ports {o_retire_inst[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_inst[0]}]
set_load -pin_load 0.1 [get_ports o_retire_trap]
set_load -pin_load 0.1 [get_ports o_retire_halt]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_raddr[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_raddr[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_raddr[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_raddr[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_raddr[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_raddr[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_raddr[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_raddr[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_raddr[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_raddr[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs1_rdata[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_rs2_rdata[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_waddr[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_waddr[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_waddr[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_waddr[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_waddr[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_rd_wdata[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_addr[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_mask[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_mask[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_mask[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_mask[0]}]
set_load -pin_load 0.1 [get_ports o_retire_dmem_ren]
set_load -pin_load 0.1 [get_ports o_retire_dmem_wen]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_rdata[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_dmem_wdata[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_pc[0]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[31]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[30]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[29]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[28]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[27]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[26]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[25]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[24]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[23]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[22]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[21]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[20]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[19]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[18]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[17]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[16]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[15]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[14]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[13]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[12]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[11]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[10]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[9]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[8]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[7]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[6]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[5]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[4]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[3]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[2]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[1]}]
set_load -pin_load 0.1 [get_ports {o_retire_next_pc[0]}]
create_clock [get_ports i_clk]  -name clk  -period 8  -waveform {0 4}
set_input_delay -clock clk  0.25  [get_ports i_rst]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[31]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[30]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[29]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[28]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[27]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[26]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[25]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[24]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[23]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[22]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[21]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[20]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[19]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[18]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[17]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[16]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[15]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[14]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[13]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[12]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[11]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[10]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[9]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[8]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[7]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[6]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[5]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[4]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[3]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[2]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[1]}]
set_input_delay -clock clk  0.25  [get_ports {i_imem_rdata[0]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[31]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[30]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[29]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[28]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[27]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[26]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[25]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[24]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[23]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[22]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[21]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[20]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[19]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[18]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[17]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[16]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[15]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[14]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[13]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[12]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[11]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[10]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[9]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[8]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[7]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[6]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[5]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[4]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[3]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[2]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[1]}]
set_input_delay -clock clk  0.25  [get_ports {i_dmem_rdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_imem_raddr[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_addr[0]}]
set_output_delay -clock clk  0.5  [get_ports o_dmem_ren]
set_output_delay -clock clk  0.5  [get_ports o_dmem_wen]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_wdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_mask[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_mask[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_mask[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_dmem_mask[0]}]
set_output_delay -clock clk  0.5  [get_ports o_retire_valid]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_inst[0]}]
set_output_delay -clock clk  0.5  [get_ports o_retire_trap]
set_output_delay -clock clk  0.5  [get_ports o_retire_halt]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_raddr[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_raddr[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_raddr[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_raddr[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_raddr[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_raddr[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_raddr[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_raddr[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_raddr[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_raddr[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs1_rdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rs2_rdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_waddr[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_waddr[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_waddr[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_waddr[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_waddr[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_rd_wdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_addr[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_mask[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_mask[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_mask[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_mask[0]}]
set_output_delay -clock clk  0.5  [get_ports o_retire_dmem_ren]
set_output_delay -clock clk  0.5  [get_ports o_retire_dmem_wen]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_rdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_dmem_wdata[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_pc[0]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[31]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[30]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[29]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[28]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[27]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[26]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[25]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[24]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[23]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[22]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[21]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[20]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[19]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[18]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[17]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[16]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[15]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[14]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[13]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[12]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[11]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[10]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[9]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[8]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[7]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[6]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[5]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[4]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[3]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[2]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[1]}]
set_output_delay -clock clk  0.5  [get_ports {o_retire_next_pc[0]}]
set_false_path   -from [get_ports i_rst]
